apiVersion: v1
kind: Service
metadata:
  name: car-demo-api
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: car-demo-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
