apiVersion: v1
kind: Service
metadata:
  name: car-demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: car-demo
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
