apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: car-demo
namespace: car-demo
resources:
  - api-deployment.yaml
  - api-service.yaml
  - app-deployment.yaml
  - app-service.yaml
  - car-dbcreation-script-configmap.yaml
  - car-demo-configmap.yaml
  - ingress.yaml
  - mariadb-secret.yaml
  - mariadb-service.yaml
  - mariadb-sts.yaml 
